### ISSUE TITLE
[TODO] Fix minor CSS issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/taotnpwaft#87]
Having a look in the console of Firefox 97, 

 > Error in parsing value for ‘width’.  Declaration dropped.
 > Elements matching selector: .TAOTContactInput [type="text"], select, textarea
 
  for the section of TAOT.css line 117-124
 
  [Recent commit fixes two other errors outside of this one.]

**Comment by gbowne1** [comment]
I also realized there are two TAOT.css

 one in /taotnpwaft/TAOT.css and the other in /taotnpwaft/website/styles/TAOT.css and there is also a TAOTtheme.css  

 the two TAOT.css files need to be diff'ed and make sure that the pages in the site links to the one in website/styles/TAOT.css

Can TAOTtheme.css be integrated into TAOT.css??

**Comment by gbowne1** [comment]
<span class="navbar-toggler-icon"></span> the responsive navbar toggler/hamburger seems to appear at 574 - 576 x (whatever)

**Comment by gbowne1** [comment]
There are a number of issues with contrast in Accessibility context.

**Comment by gbowne1** [comment]
To fix this, 

 > Error in parsing value for ‘width’. Declaration dropped.
 > Elements matching selector: .TAOTContactInput [type="text"], select, textarea

for the section of TAOT.css line 117-124
 
 I am thinking this might be better with a margin-left and margin right set to auto in that portion of the css file in this section:
```css
.TAOTContactInput [type=text], select, textarea {
    width: fit-content 100%;
    padding: 12px;
    border: 1px solid;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
}
```
